package models

import com.google.gson.annotations.SerializedName

data class State(
    @SerializedName("__all_dns_names"             ) var _allDnsNames             : ArrayList<String> = arrayListOf(),
    @SerializedName("__all_ip_addrs"              ) var _allIpAddrs              : ArrayList<String> = arrayListOf(),
    @SerializedName("__all_mac_addrs"             ) var _allMacAddrs             : ArrayList<String> = arrayListOf(),
    @SerializedName("__cdm_override_token_id"     ) var _cdmOverrideTokenId      : String?           = null,
    @SerializedName("__package_checksum"          ) var _packageChecksum         : String?           = null,
    @SerializedName("__patch_checksum"            ) var _patchChecksum           : String?           = null,
    @SerializedName("_tw_meta_data_attrs"         ) var TwMetaDataAttrs          : ArrayList<String> = arrayListOf(),
    @SerializedName("access_failure_count"        ) var accessFailureCount       : Int?              = null,
    @SerializedName("age_count"                   ) var ageCount                 : Int?              = null,
    @SerializedName("cdm_virtual_system_type"     ) var cdmVirtualSystemType     : Int?              = null,
    @SerializedName("cores_per_processor"         ) var coresPerProcessor        : Int?              = null,
    @SerializedName("cpe_id"                      ) var cpeId                    : String?           = null,
    @SerializedName("cpe_string"                  ) var cpeString                : String?           = null,
    @SerializedName("cpe_string_23"               ) var cpeString23              : String?           = null,
    @SerializedName("cpu_resource_type"           ) var cpuResourceType          : String?           = null,
    @SerializedName("cpu_threading_enabled"       ) var cpuThreadingEnabled      : Boolean?          = null,
    @SerializedName("dns_domain"                  ) var dnsDomain                : String?           = null,
    @SerializedName("domain"                      ) var domain                   : String?           = null,
    @SerializedName("host_type"                   ) var hostType                 : String?           = null,
    @SerializedName("hostname"                    ) var hostname                 : String?           = null,
    @SerializedName("kernel"                      ) var kernel                   : String?           = null,
    @SerializedName("key"                         ) var key                      : String?           = null,
    @SerializedName("last_access_response"        ) var lastAccessResponse       : String?           = null,
    @SerializedName("last_update_failure"         ) var lastUpdateFailure        : String?           = null,
    @SerializedName("last_update_success"         ) var lastUpdateSuccess        : String?           = null,
    @SerializedName("local_fqdn"                  ) var localFqdn                : String?           = null,
    @SerializedName("logical_ram"                 ) var logicalRam               : Int?              = null,
    @SerializedName("model"                       ) var model                    : String?           = null,
    @SerializedName("name"                        ) var name                     : String?           = null,
    @SerializedName("new_endpoint_identity_count" ) var newEndpointIdentityCount : Int?              = null,
    @SerializedName("no_response_count"           ) var noResponseCount          : Int?              = null,
    @SerializedName("num_cores"                   ) var numCores                 : Int?              = null,
    @SerializedName("num_logical_processors"      ) var numLogicalProcessors     : Int?              = null,
    @SerializedName("num_processors"              ) var numProcessors            : Int?              = null,
    @SerializedName("nvd_url_part"                ) var nvdUrlPart               : String?           = null,
    @SerializedName("os"                          ) var os                       : String?           = null,
    @SerializedName("os_arch"                     ) var osArch                   : String?           = null,
    @SerializedName("os_build"                    ) var osBuild                  : String?           = null,
    @SerializedName("os_class"                    ) var osClass                  : String?           = null,
    @SerializedName("os_edition"                  ) var osEdition                : String?           = null,
    @SerializedName("os_type"                     ) var osType                   : String?           = null,
    @SerializedName("os_vendor"                   ) var osVendor                 : String?           = null,
    @SerializedName("os_version"                  ) var osVersion                : String?           = null,
    @SerializedName("package_count"               ) var packageCount             : Int?              = null,
    @SerializedName("patch_count"                 ) var patchCount               : Int?              = null,
    @SerializedName("processor_speed"             ) var processorSpeed           : Int?              = null,
    @SerializedName("processor_type"              ) var processorType            : String?           = null,
    @SerializedName("processor_vendor"            ) var processorVendor          : String?           = null,
    @SerializedName("ram"                         ) var ram                      : Int?              = null,
    @SerializedName("serial"                      ) var serial                   : String?           = null,
    @SerializedName("threads_per_core"            ) var threadsPerCore           : Int?              = null,
    @SerializedName("type"                        ) var type                     : String?           = null,
    @SerializedName("uuid"                        ) var uuid                     : String?           = null,
    @SerializedName("vendor"                      ) var vendor                   : String?           = null,
    @SerializedName("virtual"                     ) var virtual                  : Boolean?          = null,
    @SerializedName("vm_class"                    ) var vmClass                  : String?           = null

)
